package com.gridlayer.db.gridlayer_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE GridBase PLEASE EDIT ../Grid.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Grid object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.math.BigDecimal;


import org.springframework.jdbc.core.RowMapper;
import com.gridlayer.db.gridlayer_db.entity.Grid;

public class GridBase implements RowMapper<Grid>{
	
	private Long _id;
	
	// Attributes
    private Double grid_id;
    private String grid_name;
    private Double grid_port;
    private String grid_trustkey;
    private String grid_uid;
	
	
	
	@Override
	public Grid mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Grid obj = new Grid();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setGrid_id(rs.getDouble("grid_id"));
			obj.setGrid_name(rs.getString("grid_name"));
			obj.setGrid_port(rs.getDouble("grid_port"));
			obj.setGrid_trustkey(rs.getString("grid_trustkey"));
			obj.setGrid_uid(rs.getString("grid_uid"));
			
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public Number getGrid_id() {
		return grid_id;
	}


	public void setGrid_id(Number grid_id) {
		this.grid_id = grid_id;
	}
	public String getGrid_name() {
		return grid_name;
	}


	public void setGrid_name(String grid_name) {
		this.grid_name = grid_name;
	}
	public Number getGrid_port() {
		return grid_port;
	}


	public void setGrid_port(Number grid_port) {
		this.grid_port = grid_port;
	}
	public String getGrid_trustkey() {
		return grid_trustkey;
	}


	public void setGrid_trustkey(String grid_trustkey) {
		this.grid_trustkey = grid_trustkey;
	}
	public String getGrid_uid() {
		return grid_uid;
	}


	public void setGrid_uid(String grid_uid) {
		this.grid_uid = grid_uid;
	}
	
    
    
    
    
}